/* ============================================================================
   SUNERGYX — HOMEPAGE CATEGORY TILES
   ============================================================================
   Generated by admin.html on 2026-10-04.
   Replace this file on your website to update the homepage tiles.
   products.js and shipping.js are not affected.

   key = product category (do not rename) | title = text on the tile
   image = image URL | visible = show/hide | order = position (0 first)
   ============================================================================ */

window.SUNERGYX_TILES = [
  {
    "key": "Combos",
    "title": "Solar Generators",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791130878/Itel-Solar-Power-Tank-.jpg",
    "visible": true,
    "order": 0
  },
  {
    "key": "Panels",
    "title": "Solar Panels",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791114390/003-300x300.jpg",
    "visible": true,
    "order": 1
  },
  {
    "key": "Inverters",
    "title": "Inverters",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791114869/felicity.webp",
    "visible": true,
    "order": 2
  },
  {
    "key": "Batteries",
    "title": "Batteries",
    "image": "https://res.cloudinary.com/ny0or3ln/image/upload/v1790635769/10KWhg_fmpy4h.png",
    "visible": true,
    "order": 3
  },
  {
    "key": "Controllers",
    "title": "Charge Controllers",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791114729/Fronius_Symo_advanced_solar_inverter_copy__04966.webp",
    "visible": true,
    "order": 4
  },
  {
    "key": "Breakers",
    "title": "Breakers & Protection",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791115000/modulinis-apsauginis-nuolatines-itampos-automatinis-jungiklis-saules-moduliams-2p-40a-1000vdc-6ka-din-kopija-4-1-1-1-1.png",
    "visible": true,
    "order": 5
  },
  {
    "key": "Appliances",
    "title": "Energy Saving Appliances",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791130626/application.png",
    "visible": true,
    "order": 6
  },
  {
    "key": "Accessories",
    "title": "Solar protection and Security",
    "image": "https://res.cloudinary.com/haqeg3gc/image/upload/v1791115103/images.jpg",
    "visible": true,
    "order": 7
  }
];
